@secret=specialsecret
@oauthcode=oauthcode
### verify merchant account

### oauth
POST https://accesstest.authorize.net/oauth/v1/token?grant_type=authorization_code&code={{otoken}}&client_id=kbQv0P5C2N&client_secret={{osecret}}&platform=2 HTTP/1.1

#