# see ./settings.js for template for variables
### get iowa json
GET https://re-store.funktechno.com/iowa-json.php HTTP/1.1

# saves an image from .. and return as base64str
### nodejs map scraper
GET http://localhost:3000/scrape?zoom=15&lat=38.9092&long=-77.0344 HTTP/1.1

### live url
GET https://scrape_re-store.serveo.net/scrape?zoom=15&lat=38.9092&long=-77.0344 HTTP/1.1

### oauth
GET {{url_oauth}}?otoken={{otoken}} HTTP/1.1

### use 1st value in array as % match and just display a % after submitting a request
GET https://re-store.funktechno.com/python/pythonrunner.php HTTP/1.1

### get requests
GET https://re-store.funktechno.com/api/get-requests.php HTTP/1.1

### get offers
GET https://re-store.funktechno.com/api/get-offers.php HTTP/1.1

###